import Footer from "components/navigation/Footer"
import Navbar from "components/navigation/Navbar"
import Layout from "hocs/layouts/Layout"
import { Helmet } from 'react-helmet-async';
import { useEffect } from "react"
import { Link } from "react-router-dom";


function PrivacyPolicy(){

    useEffect(()=>{
        window.scrollTo(0,0)
    },[])

    return(
        <Layout>
            <Helmet>
                <title>MG Seguridad Privada | Política de privacidad</title>
                <meta name="description" content="Política de privacidad de MG Seguridad Privada"/> 
                <meta name="keywords" content='politica de privacidad de mg seguridad privada, mg seguridad privada politica de privacidad'/>
                <meta name="robots" content='all'/>
                <link rel="canonical" href="https://www.mgseguridadprivada.com.ar/"/>
                <meta name="author" content="Seguridad"/>
                <meta name="publisher" content="Franco Loto"/>

                {/* Social Media Tags */}
                <meta property='og:title' content='MG Seguridad Privada'/>
                <meta property='og:description' content='Política de privacidad de MG Seguridad Privada'/>
                <meta property='og:url' content='https://www.mgseguridadprivada.com.ar/'/>
                <meta property='og:image' content='https://postimg.cc/060wgC76'/>

                <meta name="twitter:title" content='MG Seguridad Privada' />
                <meta
                    name="twitter:decription"
                    description='Política de privacidad de  MG Seguridad Privada'
                />
                <meta name="twitter:image" content="https://postimg.cc/060wgC76"/>
                <meta name="twitter:card" content="summary_large_image"/>

            </Helmet>
            <Navbar/>
            <div className="pt-40">
                <div className="mb-14 prose prose-lg max-w-6xl prose-indigo mx-auto mt-6 text-gray-500">
                <b><h3 className="text-center">Política de privacidad de MG Seguridad Privada</h3></b><br/>
                MG Seguridad Privada te informa sobre su Política de Privacidad respecto del tratamiento y protección de los datos de carácter personal de los usuarios y clientes que puedan ser recabados por la navegación o contratación de servicios a través del sitio Web www.mgseguridadprivada.com.ar/.<br/>
                MG Seguridad Privada respeta su derecho de privacidad. Esta política resume qué información personal podemos recoger, de qué manera podemos utilizar esta información y otros temas importantes relacionados con su privacidad y protección de datos.

                Es política de MG Seguridad Privada cumplir con todas las leyes de privacidad y de protección de datos vigentes. Este compromiso refleja el valor que le damos al hecho de obtener y conservar la confianza de nuestros clientes, socios comerciales y demás personas que comparten su información personal con nosotros.

                Esta Política se aplica a todos los Sitios de Internet y aplicaciones móviles administrados por MG Seguridad Privada o en su nombre, e incluye las compañias de MG Seguridad Privada de todo el mundo (conocidas como “Sitio de Internet o Aplicación Móvil de MG Seguridad Privada”). También se aplica a toda la información personal que MG Seguridad Privada pueda recoger de cualquier otro modo: (i) a través de nuestros productos y servicios; (ii) cuando interactúa con nosotros por medios distintos de un Sitio de Internet o Aplicación Móvil de MG Seguridad Privada, por ejemplo, de manera presencial, por teléfono o en una feria de muestras o formación; y (iii) a través de nuestros clientes, distribuidores, proveedores, vendedores y otros socios comerciales (en conjunto, “Socios Comerciales”).

                No obstante, los Sitios de Internet, Aplicaciones Móviles, productos y servicios de MG Seguridad Privada pueden tener fines y características distintas. Si se necesita proporcionar información adicional o diferente para un determinado Sitio de Internet, Aplicación Móvil, producto o servicio específico de MG Seguridad Privada, se publicará dicha obligación por separado en el Sitio de Internet, Aplicación Móvil, producto o servicio que sea pertinente. Cada una de estas obligaciones de proporcionar información adicionales, políticas o declaraciones de privacidad específicas (“Declaración de Privacidad Específica”) complementan y enmiendan esta Política.<br/><br/>
                <b>Principios generales de recogida, uso y divulgación de información personal por parte de MG Seguridad Privada</b><br/>
                <br/>En la medida que así lo requiera la legislación vigente, siempre que MG Seguridad Privada recoja información personal:<br/>
                <ul>
                    <li>le notificará de forma oportuna y adecuada el uso de sus datos por parte de MG Seguridad Privada;</li>
                    <li>recogerá su información personal solo para fines específicos y legítimos. La información que recojamos será pertinente, adecuada y no excesiva para los fines para los que se recoja;</li>
                    <li>tratará su información personal de manera consistente con los fines para los cuales se recogió originalmente o para los que usted otorgó posteriormente su consentimiento;</li>
                    <li>adoptará las medidas comerciales razonables para garantizar que su información personal sea fiable, exacta y completa para el uso previsto y, cuando corresponda, actualizada;</li>
                    <li>no utilizará su información personal para el envío de comunicaciones comerciales de forma directa sin darle la oportunidad de “decir que no”;</li>
                    <li>adoptará las medidas adecuadas, por contrato o de cualquier otra forma, para garantizar una protección adecuada de la información personal que se divulgue a terceros o se transfiera a otro país, incluidas las transferencias internas dentro de MG Seguridad Privada.</li>
                </ul><br/>
                <b>Información personal recogida por MG Seguridad Privada</b><br/><br/>
                MG Seguridad Privada recoge los siguientes tipos de información personal:<br/>
                <ul>
                    <li>Información proporcionada por usted<br/><br/>
                    MG Seguridad Privada recoge la información personal que usted nos proporciona, como por ejemplo: (i) información de contacto, como su nombre, nombre de empresa, puesto de trabajo, dirección postal, dirección de correo electrónico y número de teléfono; (ii) información adicional acerca de usted para ayudarnos a conocerle mejor, como su sexo, edad, fecha de nacimiento, nacionalidad, asociaciones profesionales y sus números de registro, información sobre el uso que hace de nuestros productos e información demográfica; (iii) comentarios, preguntas, solicitudes y pedidos que desee realizar; (iv) información financiera necesaria para el procesamiento de pagos si realiza compras, como datos de tarjetas de créditos o cuentas o el número de identificación fiscal; (v) información de inicio de sesión, incluyendo, si procede, información de cuentas de redes sociales para fines de inicio de sesión; e (vi) información acerca de sus preferencias, como sus métodos preferidos de comunicación y tipos de productos que le interesan.</li>
                    <li>Información recogida automáticamente de su equipo<br/><br/>
                    <b>Información sobre el equipo y el navegador:</b> MG seguridad Privada puede recoger información técnica sobre su equipo, tal y como el tipo de equipo, tipo de navegador, dirección IP, sistema operativo e identificador del equipo. MG Seguridad Privada recoge automáticamente esta información de su equipo y navegador web mediante cookies y tecnologías similares.
                    <br/><b>Información sobre el modo en que se relaciona con nosotros:</b> MG Seguridad Privada puede recoger datos técnicos sobre el uso que hace de los Sitios de Internet y Aplicaciones Móviles de MG Seguridad Privada, así como sobre el modo en que interactúa con nuestros anuncios publicitarios y promociones digitales, tal y como el contenido visto o descargado, preferencias utilizadas, enlaces visitados, correos promocionales de MG Seguridad Privada abiertos y la fecha y hora de las interacciones. MG Seguridad Privada recoge esta información mediante cookies y tecnologías similares.
                    <br/><b>Información sobre su ubicación:</b> MG Seguridad Privada puede recoger información sobre su ubicación, tal y como información precisa y en tiempo real sobre su ubicación a partir de su equipo e información imprecisa sobre la ubicación a partir de, por ejemplo, su dirección IP o código postal. Las aplicaciones de MG Seguridad Privada NO accederán a información precisa y en tiempo real sobre la ubicación a partir de su equipo salvo que nos autorice para ello.</li>
                    <li>Cookies y tecnologías similares<br/>
                    Una “cookie” es un archivo de información que se instala en su equipo cuando visita un sitio web. Las cookies y tecnologías similares pueden mejorar su experiencia de usuario al guardar sus preferencias, personalizar su experiencia online, almacenar artículos en su carrito de compras y, en algunas ocasiones, proporcionarle anuncios publicitarios adaptados a sus intereses.</li>
                </ul>
                <h3>Más información</h3><br/>
                Los sitios de Internet de MG Seguridad Privada usan “cookies de sesión”. Una cookie de sesión no le identifica de forma individual y caduca cuando se cierra el explorador. Por ejemplo, al utilizar el catálogo de productos de MG Seguridad Privada, se instala una cookie de sesión para guardar las páginas que ha visitado. Podemos utilizar esta información para ofrecerle recomendaciones de otros productos que puedan interesarle.
                Los sitios de Internet de MG Seguridad Privada también usan “cookies persistentes”. Estas cookies no caducan cuando se cierra el navegador. Las cookies persistentes permanecen en su ordenador hasta que usted las elimina o caduquen. Al asignarle un identificador exclusivo a su ordenador, podemos crear una base de datos de sus preferencias y elecciones anteriores que se pueden proporcionar automáticamente, lo que le ahorra tiempo y trabajo en futuras visitas. Por ejemplo, después de hacer una compra, si decide hacer otra compra, es posible que su dirección de envío se haya conservado y solo necesite confirmarla.
                Algunos países requieren que otorgue su consentimiento para el uso de cookies cuando visita Sitios de Internet de 3M. Si accede a un Sitio de Internet de 3M de alguno de estos países, se le mostrará información acerca de las opciones que tiene, incluyendo la opción de aceptar o rechazar determinadas categorías de cookies. Podrá cambiar estos ajustes en visitas posteriores. Tenga en cuenta que no podrá deshabilitar la recepción de las cookies que sean estrictamente necesarias para la prestación de un servicio que haya solicitado.
                En cualquier momento que visite un Sitio de Internet de 3M de alguno de estos países, al hacer clic en el enlace “Preferencias de cookies” en la parte inferior de cada página, podrá acceder a información sobre las cookies y cambiar su configuración.   
                Si bien no tiene la obligación de aceptar cookies cuando visita un Sitio de Internet de MG Seguridad Privada, es posible que no pueda utilizar todas las funciones del sitio si ha rechazado determinadas cookies.
                Además, su navegador puede permitirle ajustar la configuración para aceptar o rechazar cookies, o enviarle alertas cuando una cookie se instale en su equipo.<br/>
                <b>Análisis y acciones publicitarias.</b> MG Seguridad Privada usa servicios de análisis de terceros para comprender mejor el uso que los usuarios hacen de los Sitios de Internet y Aplicaciones Móviles de 3M, como por ejemplo, servicios prestados por Google y Adobe. Consulte los siguientes enlaces para obtener más información acerca del modo en que Google y Adobe recogen y utilizan datos cuandousted visita los sitios web o aplicaciones móviles de sus partners:
                <ul>
                    <li>www.google.com/policies/privacy/partners/</li>
                    <li>http://www.adobe.com/privacy/marketing-cloud.html</li>
                </ul>
                MG Seguridad Privada también utiliza servicios publicitarios de terceros para ofrecer anuncios publicitarios de productos o servicios de MG Seguridad Privada que puedan interesarle cuando visita sitios web u otros servicios online.
                MG Seguridad Privada permite que determinados terceros con los que trabaja, como los que prestan los servicios de análisis y publicidad mencionados, instalen cookies en nuestros Sitios de Internet. Dichos terceros pueden recoger información acerca de sus actividades online a lo largo del tiempo y en cualquier sitio web de terceros.
                Los terceros pueden ser miembros de grupos autorregulados del sector, como la Network Advertising Initiative (NAI), la Digital Advertising Alliance (DAA) o la European Digital Advertising Alliance (eDAA). Los sitios web de estos grupos ofrecen más información sobre la publicidad online adaptada a intereses o el modo de deshabilitar la recepción de anuncios online adaptados a intereses por parte de las empresas participantes.
                <h3>Cómo utiliza MG Seguridad Privada su información personal</h3><br/>
                MG Seguridad Privada puede usar su información personal para:
                <ul>
                    <li><b>Desarrollar y administrar la relación que mantenemos con usted y nuestros Socios Comerciales.</b>Esto puede incluir: (i) prestar servicios o efectuar operaciones que usted o nuestros Socios Comerciales hayan solicitado; (ii) proporcionar información acerca de productos, servicios y operaciones de MG Seguridad Privada, así como de anuncios publicitarios que puedan interesarle; (iii) ofrecerle a usted y a nuestros Socios Comerciales una experiencia más uniforme durante las interacciones con MG Seguridad Privada, por ejemplo, mediante un conocimiento más detallado del modo en que usa e interactúa con los Sitios de Internet, Aplicaciones Móviles, productos y servicios de MG Seguridad Privada; y (iv) planificar, administrar y operar con arreglo a la relación contractual que mantenemos con nuestros Socios Comerciales.</li>
                    <li><b>Comunicarse con usted o su empresa.</b>Esto puede incluir: (i) informarle de productos, servicios y actividades promocionales de MG Seguridad Privada que puedan interesarle a usted o a su empresa; (ii) ofrecer información acerca de productos, servicios y operaciones pertinentes de MG Seguridad Privada, por ejemplo, información sobre la fijación de precios; datos técnicos; información sobre facturas, envíos o producción, información sobre garantías o retiradas de producto; o información sobre mejoras de productos o servicios; (iii) responder a preguntas o consultas que nos plantee, como solicitudes de atención al cliente; e (iv) invitarle a participar en encuestas de satisfacción del cliente o estudios de mercado o informarle de los resultados de los mismos.</li>
                    <li><b>Ofrecer y mejorar nuestros Sitios de Internet, Aplicaciones Móviles, productos y servicios.</b>Esto puede incluir: (i) adecuarlos a sus preferencias o intereses, hacerlos más compatibles con su tecnología o ampliar la facilidad de uso de cualquier otra manera; (ii) mantener la seguridad y protegerlos de otra forma; y (iii) desarrollar nuevos Sitios de Internet, Aplicaciones Móviles, productos y servicios de MG Seguridad Privada.</li>
                    <li><b>Abordar cuestiones legales.</b>Esto puede incluir: (i) cumplir con nuestras obligaciones de conservar determinados registros comerciales durante períodos de conservación mínimos; (ii) establecer, ejercer o defender derechos legales; (iii) cumplir con leyes, normas, órdenes judiciales u otros procesos legales; (iv) detectar, prevenir y responder a fraudes, vulneraciones de la propiedad intelectual,o industrial, incumplimiento de nuestros contratos o acuerdos, incumplimiento de la ley o cualquier otro uso indebido de los Sitios de Internet, Aplicaciones Móviles, productos o servicios de MG Seguridad Privada; y (iv) proteger los derechos o propiedad de MG Seguridad Privada, o la salud, seguridad, bienestar, derechos o propiedad de usted u otros.</li>
                </ul>
                MG Seguridad Privada también puede utilizar su información personal para otros usos consistentes con el contexto en que la información se recogió con su consentimiento.<br/>
                MG Seguridad Privada puede anonimizar o agregar cualquier información recogida y usarla para cualquier fin, como, por ejemplo, investigar y desarrollar nuevos productos. Esta información no servirá para identificarle personalmente.<br/>
                <h3>Cuándo puede MG Seguridad Privada compartir su información personal</h3><br/>
                MG Seguridad Privada no revelará información personal que tenga suya, excepto en los casos que se describen a continuación:
                <ul>
                    <li>MG Seguridad Privada puede compartir su información personal con otras entidades de MG Seguridad Privada, incluyendo aquellas que se encuentren ubicadas en otros países. Cuando lo hagamos, estas otras entidades de MG Seguridad Privada utilizarán su información de manera consistente con esta Política, todas las Declaraciones de Privacidad Específicas vigentes y todas las leyes de protección de datos y privacidad vigentes.</li>
                    <li>MG Seguridad Privada también puede compartir su información personal con terceros que contratemos para que nos presten servicios de apoyo. Dichos terceros tienen la obligación de utilizar la información personal que hayamos compartido con ellos solo para prestar los servicios objeto del contrato en nuestro nombre y tratar su información personal con arreglo a todas las leyes de protección de datos y privacidad vigentes.</li>
                    <li>En algunos casos, MG Seguridad Privada puede compartir su información personal con terceros que estén asociados con nosotros para proporcionar productos y servicios a nuestros clientes, por ejemplo, distribuidores. En tal caso, exigiremos que nuestros Socios Comerciales usen dicha información de manera consistente con esta Política, todas las Declaraciones de Privacidad Específicas vigentes y todas las leyes de protección de datos y privacidad vigentes.</li>
                    <li>MG Seguridad Privada también puede compartir su información personal con terceros cuando creamos de buena fe que la divulgación sea necesaria para: (i) cumplir con una ley, norma, orden judicial u otro proceso legal; (ii) detectar, prevenir y responder a fraudes, vulneraciones de la propiedad intelectual o industrial, incumplimiento de nuestros contratos o acuerdos, incumplimientos de la ley o cualquier otro uso indebido de los Sitios de Internet, Aplicaciones Móviles, productos o servicios de MG Seguridad Privada; (iii) proteger los derechos o la propiedad de MG Seguridad Privada, o la salud, seguridad, bienestar, derechos y propiedad de usted u otros; o (iv) en circunstancia similares. Si se produce alguno de estos supuestos, tomaremos las medidas oportunas para proteger su información personal.</li>
                    <li>MG Seguridad Privada puede compartir su información personal con terceros en relación con la venta, compra, fusión, reorganización, liquidación o disolución de MG Seguridad Privada o de una unidad comercial de MG Seguridad Privada, o en circunstancias similares. Si se produce alguno de estos supuestos, tomaremos las medidas oportunas para proteger su información personal.</li>
                    <li>MG Seguridad Privada puede compartir su información con su permiso o si usted lo solicita.</li>
                </ul>
                MG Seguridad Privada puede compartir información anonimizada o agregada de manera interna y con terceros para cualquier fin. Con esta información no será posible identificarle personalmente.
                <h3>Seguridad de su información personal</h3><br/>
                En general, su información personal se almacenará en las bases de datos de MG Seguridad Privada o en las bases de datos que mantengan nuestros proveedores de servicios. Muchas de estas bases de datos se almacenan en servidores que se encuentran ubicados en Estados Unidos. MG Seguridad Privada adopta las medidas adecuadas, por contrato o de otra forma, para proporcionar protección suficiente a la información personal que proporciona a terceros o que transfiere a otro país, incluyendo en el caso de transferencias internas de MG Seguridad Privada.
                MG Seguridad Privada mantiene medidas de seguridad razonables para proteger la confidencialidad, seguridad e integridad de su información personal. Pese a que adoptamos medidas de seguridad para ayudarnos a proteger su información personal de una divulgación no autorizada, un uso incorrecto o alteración, tal como sucede con todas las redes conectadas a Internet, no podemos garantizar la seguridad de la información transmitida por Internet y no asumimos ninguna responsabilidad por las vulneraciones de seguridad más allá de nuestro control razonable.
                <h3>Enlaces a Sitios de Internet y Plugins de terceros</h3><br/>
                Los Sitios de Internet y Aplicaciones Móviles de MG Seguridad Privada pueden contener enlaces a sitios web o aplicaciones móviles que no están controlados por MG Seguridad Privada y a plugins de plataformas de redes sociales y otros terceros. Un ejemplo en redes sociales es el botón Me Gusta de Facebook. Ofrecemos estos enlaces y plugins como un servicio y no implican ningún tipo de aprobación de las actividades o del contenido de los sitios web, aplicaciones o plataformas de redes sociales correspondientes, ni asociación con sus operadores. Para obtener más información sobre la información recogida por estos sitios web, aplicaciones móviles y plugins de terceros, consulte sus políticas de privacidad. Le animamos a que revise las políticas de privacidad de los sitios web, aplicaciones móviles y plataformas de redes sociales que visite antes de utilizarlos o de proporcionar información personal.
                <h3>Conservación de su información personal</h3><br/>
                El tiempo que conservemos su información personal variará y dependerá del objetivo y del uso de la información recogida. Existen requisitos legales que nos obligan a conservar determinados datos durante períodos de tiempo específicos. De no ser así, conservaremos dicha información durante el tiempo que sea necesario para los fines para los que se recogieron dichos datos.
                <h3>Más información</h3><br/>
                <b>Tratamiento basado en intereses comerciales legítimos.</b> Cuando tratamos información personal atendiendo a la necesidad del tratamiento para nuestros intereses comerciales legítimos, dichos intereses incluyen: (i) ofrecer, mejorar y promocionar Sitios de Internet, Aplicaciones Móviles, productos y servicios de MG Seguridad Privada; (ii) comunicarse con clientes actuales y potenciales, otros Socios Comerciales y sus puntos de contacto individuales; (iii) administrar la relación con nuestros clientes y otros Socios Comerciales y sus puntos de contacto individuales; (iv) otros fines de desarrollo empresarial; (v) compartir información dentro del grupo de MG Seguridad Privada, así como con proveedores de servicios y otros terceros; y (vi) mantener la seguridad y protección de nuestros productos, servicios y empleados, incluida la protección contra fraudes.<br/>
                <b>Tratamiento basado en el cumplimiento de un contrato.</b> Un ejemplo de una situación en la que tratamos información personal necesaria para el cumplimiento de un contrato son las operaciones de comercio electrónico en las que usted ha comprado un producto o servicio de MG Seguridad Privada en su propio nombre y desde un Sitio de Internet o Aplicación Móvil de MG Seguridad Privada.<br/>
                <b>Tratamiento basado en el consentimiento.</b> Algunos ejemplos de actividades de tratamiento para las que MG Seguridad Privada usa el consentimiento como base legal son: (i) recogida y tratamiento de información precisa sobre la ubicación de su dispositivo móvil; (ii) envío de correos electrónicos promocionales cuando se requiera consentimiento según la legislación vigente; y (iii) tratamiento de datos personales en Sitios de Internet o Aplicaciones Móviles de MG Seguridad Privada mediante cookies y tecnologías similares cuando se requiera consentimiento según la legislación vigente.<br/>
                <b>Tratamiento porque MG Seguridad Privada está legalmente obligada a hacerlo.</b> Algunos ejemplos de situaciones en las que MG Seguridad Privada debe tratar datos personales para cumplir con una obligación legal son: (i) pago de impuestos y otras tasas gubernamentales; (ii) proporcionar datos personales a organismos de seguridad y otros organismos gubernamentales cuando lo requiera la legislación vigente; (iii) conservación de registros comerciales cuya conservación sea obligatoria de conformidad con la legislación vigente; y (iv) cumplimiento con órdenes judiciales y otros procesos legales.
                <h3>Sus derechos personales</h3><br/>
                Con arreglo a la legislación vigente de los países de Latino América usted tiene los siguientes derechos en relación con sus datos personales, los cuales pueden aplicarse de forma diferente en función de las circunstancias: derecho de acceso, derecho de rectificación, derecho de supresión, derecho a la limitación del tratamiento de datos, derecho a la portabilidad de datos y derecho a oponerse al tratamiento. La mayoría de estos derechos no son absolutos. A continuación describimos estos derechos con mayor detenimiento y proporcionamos información sobre la manera de ejercerlos. Si solicita ejercer sus derechos, contestaremos a su petición en el intervalo de un mes, pero tenemos el derecho de ampliar este período otros dos meses adicionales, si fuera necesario.<br/><br/>
                <b>Derecho de acceso.</b> Tiene derecho a solicitar a MG Seguridad Privada que confirme si está tratando sus datos personales. En caso afirmativo, tiene derecho a solicitar acceso a los datos personales que tratamos sobre usted y a la siguiente información: (i) los fines del tratamiento; (ii) las categorías de datos personales que tratamos; (iii) los destinatarios o categorías de destinatarios de sus datos personales; (iv) el período de conservación previsto de los datos cuando sea posible o los criterios empleados para determinar el período de conservación; (v) su derecho a solicitar la rectificación o la supresión de sus datos personales o la limitación del tratamiento de tales datos; (vi) su derecho a presentar una reclamación ante una autoridad de control; (vii) si no hemos obtenido los datos de usted, cualquier información de la que dispongamos acerca del origen de los datos; y (viii) si usamos sus datos personales para tomar decisiones automatizadas con efectos significativos de carácter legal u otra naturaleza sobre usted.<br/>
                <b>Derecho de rectificación.</b> Tiene derecho a la rectificación de los datos personales que MG Seguridad Privada tenga de usted cuando éstos sean inexactos. Teniendo en cuenta los fines del tratamiento, también tiene derecho a que se completen los datos personales acerca de usted que estén incompletos, inclusive mediante una declaración adicional.<br/>
                <b>Derecho a oponerse al tratamiento por intereses comerciales legítimos de MG Seguridad Privada.</b> Tiene derecho a oponerse a que MG Seguridad Privada trate sus datos personales cuando el tratamiento de dichos datos se efectúe atendiendo a intereses comerciales legítimos de MG Seguridad Privada. MG Seguridad Privada respetará su oposición y dejará de tratar los datos personales pertinentes, a menos que: (i) tengamos motivos legítimos que nos obliguen a que el tratamiento prevalezcan sobre sus intereses, derechos y libertades; o (ii) necesitemos seguir tratando sus datos personales para establecer, ejercer o defender una reclamación.<br/>
                <b>Derecho a oponerse al tratamiento para el envío de comunicaciones comerciales.</b> Si MG Seguridad Privada trata sus datos personales para el envío de comunicaciones comerciales , tiene derecho a oponerse a este tratamiento. Si ejerce este derecho, MG Seguridad Privada dejará de tratar sus datos personales para el envío de comunicaciones comerciales.<br/>
                <b>Derecho a la limitación del tratamiento.</b> Tiene derecho a solicitar que MG Seguridad Privada limite el tratamiento de sus datos personales en las siguientes circunstancias: (i) durante el período de tiempo que MG Seguridad Privada necesite para verificar la exactitud de sus datos personales cuando usted impugne su exactitud; (ii) cuando el tratamiento de sus datos personales sea ilícito y usted se oponga a la supresión de los datos y en su lugar solicite a MG Seguridad Privada la limitación de su uso; (iii) cuando MG Seguridad Privada ya no necesite sus datos personales para los fines del tratamiento, pero usted necesite los datos para la formulación, el ejercicio o la defensa de reclamaciones; o (iv) durante el período de tiempo que MG Seguridad Privada necesite para verificar si tiene un motivo legítimo que prevalezca sobre sus intereses, derechos y libertades cuando usted se oponga al tratamiento de sus datos personales con fines comerciales legítimos por parte de MG Seguridad Privada.
                Si MG Seguridad Privada limita el tratamiento de sus datos personales atendiendo a una solicitud presentada por usted, MG Seguridad Privada guardará sus datos y los tratará de solo: (i) con su consentimiento; (ii) para la formulación, el ejercicio o la defensa de reclamaciones; (iii) para proteger los derechos de otra personal física o jurídica; o (iv) por razones de interés público de la Unión Europea o un Estado miembro. MG Seguridad Privada también le informará antes de eliminar la limitación del tratamiento.<br/>
                <b>Derecho a la supresión.</b> El derecho a la supresión también se conoce como “derecho al olvido”. Puede solicitar a MG Seguridad Privada que elimine sus datos personales. Este derecho no es absoluto. MG Seguridad Privada solo está obligada a eliminar sus datos personales bajo su solicitud en las siguientes circunstancias: (i) sus datos personales ya no son necesarios para los fines para los que MG Seguridad Privada los recogió o trató; (ii) si MG Seguridad Privada trata sus datos personales basándose en el consentimiento, usted retira el consentimiento y no existe ningún otro fundamento legal para que MG Seguridad Privada siga tratando sus datos personales; (iii) si MG Seguridad Privada trata sus datos personales con fines comerciales legítimos, usted se opone al tratamiento y MG Seguridad Privada no tiene motivos jurídicos que prevalezcan para continuar con el tratamiento de sus datos personales; (iv) si MG Seguridad Privada ha tratado sus datos personales de manera ilegal; o (v) los datos personales deban suprimirse para cumplir con una obligación legal con arreglo a la legislación de la Unión Europea o de un Estado Miembro a la que MG Seguridad Privada está sujeta.
                MG Seguridad Privada no está obligada a suprimir sus datos personales en la medida en que MG Seguridad Privada necesite tratarlos para: (i) ejercer su derecho a la libertad de expresión e información; (ii) cumplir con una obligación legal con arreglo a la legislación de la Unión Europea o de un Estado miembro a la que MG Segurida Privada esté sujeta; o (iii) para la formulación, el ejercicio o la defensa de reclamaciones.<br/>
                <b>Derecho a la portabilidad de datos.</b> Tiene derecho a recibir los datos personales que haya proporcionado a MG Seguridad Privada cuando: (i) el tratamiento de los datos se base en su consentimiento o sea necesario para el cumplimiento de un contrato entre usted y MG Seguridad Privada; (ii) el tratamiento de sus datos personales por parte de MG Seguridad Privada se efectúe de manera automatizada; y (iii) el cumplimiento de la solicitud no afecte de manera negativa a los derechos y libertades de otras personas. Si tiene derecho a recibir estos datos personales y solicita a MG Seguridad Privada que se los proporcione, MG Seguridad Privada se los proporcionará en un formato estructurado, conocido y legible por máquinas.<br/>
                <b>Derecho a presentar una reclamación ante una autoridad de control.</b> MG Seguridad Privada realizará sus mejores esfuerzos para abordar y solucionar cualquier solicitud o reclamación recibida a su atención. Además, usted tiene derecho a plantear solicitudes y quejas a la autoridad de protección de datos competente. Puede tratarse de la autoridad de control del país o estado federal en el que resida.
                <h3>Preguntas acerca de esta Política o de nuestras Declaraciones de Privacidad</h3><br/>
                Si tiene alguna pregunta acerca de esta Política, de una Declaración de Privacidad Específica o del uso que hacemos de su información personal, puede ponerse contacto con MG Seguridad Privada:<br/><br/>

                Dirección: Ruta Nacional 251 KM 117,5 General Conesa, Río Negro, Argentina.<br/>
                Teléfono: +54 2920 248332<br/>
                Email: MGseguridadprivada2017@hotmail.com<br/>
                <h3>Cambios en esta Política y nuestras Declaraciones de Privacidad</h3><br/>
                Los cambios en esta Política de Privacidad se publicarán en esta página web, junto con información sobre cualquier cambio material. MG Seguridad Privada se reserva el derecho de actualizar o modificar esta Política y las Declaraciones de Privacidad Específicas en cualquier momento y sin previo aviso. Las modificaciones se aplicarán solo a la información personal que recojamos tras la publicación.
                Esta Política se revisó por última vez en Junio de 2023.<br/>
                <hr/>
                <b>Enlaces Relacionados</b><br/><br/>
                <Link to="/terms">Términos y condiciones</Link><br/>
                <Link to="/contacto">Envíanos un mensaje</Link>
                </div>
            </div>
            <Footer/>
        </Layout>
    )
}

export default PrivacyPolicy